theme: jekyll-theme-slate
title: Exemples et exercices des cours
description: Dépôt des exercices et exemples présentés dans le cadre de mes cours (CC-BY-4.0 License)
author: Alexandre Meyer
avatar: "avatar.png"
